const DEUSES = [
    {
        nome: "Zeus",
        nomeRomano: "Júpiter",
        emoji: "⚡",
        tipo: "olimpiano",
        dominio: "Rei dos deuses, céu, trovão e relâmpago",
        simbolos: ["Raio", "Águia", "Carvalho", "Cetro"],
        historia: "Zeus é o deus supremo do Olimpo, governante dos céus e da terra. Filho de Cronos e Reia, foi salvo pela mãe de ser devorado pelo pai. Cresceu em segredo na ilha de Creta e, ao atingir a maturidade, libertou seus irmãos do estômago de Cronos. Liderou a Titanomaquia, a guerra contra os Titãs, e após a vitória dividiu o cosmos com seus irmãos: ficou com os céus, Poseidon com os mares e Hades com o submundo. Conhecido por seus inúmeros casos amorosos e filhos, Zeus é tanto justo quanto temperamental, lançando raios contra quem desafia sua autoridade.",
        poderes: ["Controle dos raios e trovões", "Metamorfose", "Imortalidade", "Onisciência parcial"],
        curiosidades: "Zeus se transformava em diversas formas para se aproximar de mortais e deusas — já foi touro, cisne, chuva de ouro e até formiga."
    },
    {
        nome: "Hera",
        nomeRomano: "Juno",
        emoji: "👑",
        tipo: "olimpiano",
        dominio: "Rainha dos deuses, casamento e família",
        simbolos: ["Pavão", "Vaca", "Romã", "Diadema"],
        historia: "Hera é a rainha do Olimpo, esposa e irmã de Zeus. Protetora do casamento e da fidelidade conjugal, vivia atormentada pelas infidelidades do marido. Sua vingança era temível — perseguiu várias amantes e filhos ilegítimos de Zeus, incluindo Héracles. Apesar de seu ciúme, Hera era profundamente respeitada e adorada como a deusa da família, do parto e da lealdade. Seu casamento sagrado com Zeus era celebrado em grandes festivais.",
        poderes: ["Proteção do matrimônio", "Maldições terríveis", "Fertilidade", "Comando sobre o Olimpo"],
        curiosidades: "O pavão é seu animal sagrado porque tem 'olhos' nas penas — representando Argos Panoptes, o gigante de cem olhos que ela colocou para vigiar uma amante de Zeus."
    },
    {
        nome: "Poseidon",
        nomeRomano: "Netuno",
        emoji: "🔱",
        tipo: "olimpiano",
        dominio: "Mares, terremotos e cavalos",
        simbolos: ["Tridente", "Cavalo", "Golfinho", "Touro"],
        historia: "Poseidon é o senhor dos mares e oceanos, irmão de Zeus e Hades. Após a derrota dos Titãs, recebeu o domínio das águas. É temperamental como o mar — pode ser calmo e generoso ou furioso e destrutivo. Criou os cavalos a partir da espuma do mar e disputou com Atena pela patronagem de Atenas, oferecendo uma fonte de água salgada enquanto ela ofereceu a oliveira. Perdeu a disputa, mas seu poder sobre os mares permaneceu incontestável.",
        poderes: ["Controle dos oceanos e marés", "Causar terremotos", "Criar cavalos e criaturas marinhas", "Tempestades"],
        curiosidades: "Poseidon construiu os muros de Troia, mas quando o rei Laomedonte se recusou a pagá-lo, enviou um monstro marinho para devastar a cidade."
    },
    {
        nome: "Atena",
        nomeRomano: "Minerva",
        emoji: "🦉",
        tipo: "olimpiano",
        dominio: "Sabedoria, guerra estratégica e artesanato",
        simbolos: ["Coruja", "Oliveira", "Escudo (Égide)", "Lança"],
        historia: "Atena nasceu da cabeça de Zeus já adulta e armada, após ele engolir sua mãe Métis grávida. É a deusa da sabedoria, da estratégia militar e das artes. Diferente de Ares, representa a guerra inteligente e planejada. Padroeira de Atenas, ofereceu a oliveira como presente à cidade. É virgem por escolha, dedicando-se à justiça e ao conhecimento. Ajudou heróis como Perseu, Odisseu e Héracles em suas jornadas.",
        poderes: ["Sabedoria suprema", "Estratégia militar", "Artes e artesanato", "Transformação"],
        curiosidades: "Atena transformou Aracne em aranha após a mortal ousar desafiá-la em uma competição de tecelagem — e vencer."
    },
    {
        nome: "Apolo",
        nomeRomano: "Apolo",
        emoji: "☀️",
        tipo: "olimpiano",
        dominio: "Sol, música, poesia, profecia e cura",
        simbolos: ["Lira", "Arco e flecha", "Louros", "Sol"],
        historia: "Apolo é o deus da luz, da música, da poesia, da cura e da profecia. Filho de Zeus e Leto, irmão gêmeo de Ártemis. É o mais belo dos deuses e patrono do Oráculo de Delfos, onde a Pitonisa transmitia suas profecias. Músico supremo, venceu Mársias em um duelo musical. Apolo também é associado à medicina — seu filho Asclépio se tornou o deus da cura. Apesar de sua luz, teve amores trágicos, como Dafne (transformada em loureiro) e Jacinto.",
        poderes: ["Profecia", "Cura e pestilência", "Música divina", "Arquearia perfeita"],
        curiosidades: "Apolo manteve o mesmo nome na mitologia romana — um dos poucos deuses gregos que não teve o nome alterado."
    },
    {
        nome: "Ártemis",
        nomeRomano: "Diana",
        emoji: "🏹",
        tipo: "olimpiano",
        dominio: "Caça, lua, natureza selvagem e castidade",
        simbolos: ["Arco e flecha", "Cervo", "Lua crescente", "Cipreste"],
        historia: "Ártemis é a deusa da caça, da lua e protetora da natureza selvagem e dos animais. Irmã gêmea de Apolo, nasceu primeiro e ajudou no parto do irmão. Pediu a Zeus para permanecer virgem eternamente e percorre as florestas com suas ninfas caçadoras. É protetora das mulheres jovens e dos partos, apesar de nunca ter sido mãe. Feroz com quem desrespeita a natureza ou sua castidade — transformou Actéon em cervo quando ele a viu banhando-se.",
        poderes: ["Caça suprema", "Controle lunar", "Proteção da natureza", "Transformação"],
        curiosidades: "Ártemis pediu a Zeus seis desejos quando criança: castidade eterna, um arco e flechas, o título de 'Portadora da Luz', uma túnica curta para caçar, sessenta ninfas como companheiras e todas as montanhas do mundo."
    },
    {
        nome: "Ares",
        nomeRomano: "Marte",
        emoji: "⚔️",
        tipo: "olimpiano",
        dominio: "Guerra, violência e coragem",
        simbolos: ["Lança", "Escudo", "Abutre", "Javali"],
        historia: "Ares é o deus da guerra, da violência e do derramamento de sangue. Filho de Zeus e Hera, era o deus menos querido do Olimpo — até seus pais o desprezavam. Diferente de Atena, que representava a estratégia, Ares personificava a brutalidade da guerra. Teve um longo caso com Afrodite, esposa de Hefesto, que os expôs diante dos deuses. Apesar de sua reputação, era pai devotado e protetor feroz de seus filhos.",
        poderes: ["Força sobre-humana", "Fúria de guerra", "Invulnerabilidade parcial", "Incitar conflitos"],
        curiosidades: "Em Roma, Marte era muito mais respeitado que Ares na Grécia. Os romanos o consideravam pai de Rômulo e Remo, fundadores de Roma."
    },
    {
        nome: "Afrodite",
        nomeRomano: "Vênus",
        emoji: "🌹",
        tipo: "olimpiano",
        dominio: "Amor, beleza e desejo",
        simbolos: ["Rosa", "Pomba", "Espelho", "Concha"],
        historia: "Afrodite nasceu da espuma do mar quando Cronos lançou os restos de Urano nas águas. É a deusa do amor, da beleza e do desejo, capaz de fazer qualquer ser se apaixonar. Casada com Hefesto por arranjo de Zeus, manteve um famoso caso com Ares. Sua beleza era tão poderosa que causou a Guerra de Troia — ao prometer Helena a Páris em troca da maçã dourada. Mãe de Eros (Cupido), Afrodite tanto abençoa quanto castiga em questões de amor.",
        poderes: ["Induzir amor e desejo", "Beleza irresistível", "Encantamento", "Proteção dos amantes"],
        curiosidades: "A palavra 'afrodisíaco' vem de seu nome. Seu cinturão mágico, o Cestus, tornava qualquer um irresistivelmente atraente."
    },
    {
        nome: "Hefesto",
        nomeRomano: "Vulcano",
        emoji: "🔨",
        tipo: "olimpiano",
        dominio: "Forja, fogo e metalurgia",
        simbolos: ["Martelo", "Bigorna", "Tenazes", "Vulcão"],
        historia: "Hefesto é o deus ferreiro, mestre da forja e do fogo. Filho de Hera (sozinha ou com Zeus), nasceu defeituoso e foi lançado do Olimpo por sua mãe. Acolhido por Tétis no fundo do mar, aprendeu a arte da metalurgia. Criou obras-primas divinas: o escudo de Aquiles, as armas dos deuses, autômatos de ouro e a rede que capturou Afrodite e Ares. Apesar de ser o menos belo dos deuses, sua habilidade artesanal era incomparável.",
        poderes: ["Metalurgia divina", "Controle do fogo", "Criação de autômatos", "Armas encantadas"],
        curiosidades: "Hefesto criou Pandora, a primeira mulher mortal, moldando-a em argila por ordem de Zeus. Cada deus lhe deu um atributo."
    },
    {
        nome: "Hermes",
        nomeRomano: "Mercúrio",
        emoji: "🪽",
        tipo: "olimpiano",
        dominio: "Mensageiro dos deuses, comércio, viajantes e ladrões",
        simbolos: ["Caduceu", "Sandálias aladas", "Capacete alado", "Tartaruga"],
        historia: "Hermes é o mensageiro dos deuses, o mais astuto e veloz do Olimpo. Filho de Zeus e da ninfa Maia, mostrou sua esperteza desde o nascimento — ainda bebê, roubou o gado de Apolo e inventou a lira a partir de uma carapaça de tartaruga. É o guia das almas para o submundo (Psicopompo), protetor dos viajantes, comerciantes e, ironicamente, dos ladrões. Suas sandálias e capacete alados lhe permitem voar entre os mundos.",
        poderes: ["Velocidade divina", "Voo", "Eloquência", "Guia entre mundos"],
        curiosidades: "Hermes inventou o alfabeto, a astronomia, as escalas musicais, a arte da luta e a ginástica, além da lira e da flauta."
    },
    {
        nome: "Deméter",
        nomeRomano: "Ceres",
        emoji: "🌾",
        tipo: "olimpiano",
        dominio: "Colheita, agricultura e fertilidade da terra",
        simbolos: ["Trigo", "Tocha", "Porco", "Cornucópia"],
        historia: "Deméter é a deusa da colheita e da agricultura, responsável pela fertilidade da terra. Sua história mais conhecida é o rapto de sua filha Perséfone por Hades. Devastada pela perda, Deméter vagou pelo mundo em luto, fazendo a terra tornar-se estéril. Quando Perséfone foi parcialmente devolvida (passando metade do ano no submundo), Deméter criou as estações: primavera e verão quando a filha está presente, outono e inverno quando está com Hades.",
        poderes: ["Controle da fertilidade da terra", "Criar fome ou abundância", "Ciclos das estações", "Mistérios de Elêusis"],
        curiosidades: "Os Mistérios de Elêusis, os ritos secretos mais importantes da Grécia antiga, eram dedicados a Deméter e Perséfone."
    },
    {
        nome: "Dionísio",
        nomeRomano: "Baco",
        emoji: "🍇",
        tipo: "olimpiano",
        dominio: "Vinho, festividades, teatro e êxtase",
        simbolos: ["Videira", "Tirso", "Leopardo", "Máscara"],
        historia: "Dionísio é o deus do vinho, das festividades e do êxtase. Filho de Zeus e da mortal Sêmele, é o único deus olímpico com mãe mortal. Sêmele morreu ao ver Zeus em sua forma divina, e o bebê foi costurado na coxa de Zeus até o nascimento. Viajou pelo mundo ensinando o cultivo da uva e a arte do vinho. Seus seguidores, as Mênades, dançavam em frenesi selvagem. Dionísio representa a libertação, o prazer e a dissolução dos limites.",
        poderes: ["Criar vinho", "Induzir loucura ou êxtase", "Metamorfose", "Ressurreição"],
        curiosidades: "Dionísio é chamado de 'nascido duas vezes' — uma do ventre de Sêmele e outra da coxa de Zeus. O teatro grego nasceu das festas em sua honra."
    },
    {
        nome: "Hades",
        nomeRomano: "Plutão",
        emoji: "💀",
        tipo: "olimpiano",
        dominio: "Submundo, mortos e riquezas da terra",
        simbolos: ["Elmo da invisibilidade", "Cipreste", "Cerbero", "Chaves"],
        historia: "Hades é o senhor do submundo, governante dos mortos. Irmão de Zeus e Poseidon, recebeu o mundo inferior após a derrota dos Titãs. Embora temido, Hades não é maligno — é um juiz justo e guardião necessário da ordem cósmica. Raptou Perséfone para ser sua rainha, mas eventualmente se tornou um marido dedicado. Raramente deixa seu reino e é o deus mais rico, pois controla todos os minerais e metais da terra.",
        poderes: ["Invisibilidade (Elmo)", "Controle dos mortos", "Riquezas da terra", "Julgamento das almas"],
        curiosidades: "Os gregos evitavam falar seu nome por medo, chamando-o de 'Plutão' (o rico) como eufemismo. Não era considerado mau, apenas inevitável."
    },
    {
        nome: "Perséfone",
        nomeRomano: "Prosérpina",
        emoji: "🌺",
        tipo: "olimpiano",
        dominio: "Primavera, submundo e renovação",
        simbolos: ["Romã", "Flores", "Tocha", "Coroa"],
        historia: "Perséfone é a deusa da primavera e rainha do submundo. Filha de Deméter e Zeus, foi raptada por Hades enquanto colhia flores. Sua mãe, desesperada, fez a terra ficar estéril. Zeus interveio, mas Perséfone havia comido sementes de romã no submundo, ligando-se àquele lugar. O acordo: passaria metade do ano com Hades (outono/inverno) e metade com Deméter (primavera/verão). Assim nasceram as estações.",
        poderes: ["Controle da primavera", "Autoridade sobre os mortos", "Renovação e ciclos", "Transição entre mundos"],
        curiosidades: "Perséfone era tão temida como rainha do submundo quanto amada como deusa da primavera. Poucos heróis ousaram desafiá-la."
    },
    {
        nome: "Cronos",
        nomeRomano: "Saturno",
        emoji: "⏳",
        tipo: "tita",
        dominio: "Tempo, eras e colheita",
        simbolos: ["Foice", "Ampulheta", "Serpente"],
        historia: "Cronos é o titã do tempo e líder dos Titãs. Filho de Urano (Céu) e Gaia (Terra), castrou seu pai com uma foice para libertar seus irmãos. Governou durante a Idade de Ouro, mas, temendo ser destronado pelos filhos como fizera com seu pai, devorava cada um ao nascer. Reia escondeu Zeus, o caçula, que cresceu e obrigou Cronos a regurgitar os outros filhos. Na Titanomaquia, Zeus venceu e aprisionou Cronos no Tártaro.",
        poderes: ["Controle do tempo", "Força titânica", "Imortalidade"],
        curiosidades: "A Idade de Ouro sob Cronos era uma era sem guerras, sem trabalho e sem sofrimento. Em Roma, era celebrado no Saturnália, festa de alegria e igualdade."
    },
    {
        nome: "Reia",
        nomeRomano: "Ops",
        emoji: "🌍",
        tipo: "tita",
        dominio: "Maternidade, fertilidade e fluxo",
        simbolos: ["Leões", "Coroa de torres", "Tambor"],
        historia: "Reia é a titânide da maternidade e fertilidade, esposa de Cronos e mãe dos seis deuses olímpicos originais: Héstia, Deméter, Hera, Hades, Poseidon e Zeus. Quando Cronos começou a devorar seus filhos, Reia escondeu o último — Zeus — em Creta e deu a Cronos uma pedra envolta em panos para engolir. Sua astúcia salvou o futuro do Olimpo. É associada à Grande Mãe e à proteção maternal.",
        poderes: ["Fertilidade divina", "Proteção maternal", "Astúcia", "Força primordial"],
        curiosidades: "Em Creta, os Curetes (guerreiros divinos) batiam seus escudos para abafar o choro do bebê Zeus, evitando que Cronos o descobrisse."
    },
    {
        nome: "Atlas",
        nomeRomano: "Atlas",
        emoji: "🌐",
        tipo: "tita",
        dominio: "Resistência, astronomia e sustentação do céu",
        simbolos: ["Globo celeste", "Pilares"],
        historia: "Atlas é o titã condenado a sustentar o céu sobre os ombros por toda a eternidade. Líder dos Titãs na guerra contra os deuses olímpicos, após a derrota Zeus o puniu com essa tarefa eterna. É pai das Plêiades, das Hespérides e de Calipso. Héracles o visitou durante seus trabalhos, segurando o céu brevemente enquanto Atlas buscava as maçãs douradas. Atlas é associado à astronomia e à cartografia.",
        poderes: ["Força descomunal", "Conhecimento astronômico", "Resistência infinita"],
        curiosidades: "A palavra 'atlas' (livro de mapas) vem de seu nome. O Oceano Atlântico também recebeu esse nome em sua homenagem."
    },
    {
        nome: "Prometeu",
        nomeRomano: "Prometeu",
        emoji: "🔥",
        tipo: "tita",
        dominio: "Previsão, fogo e proteção da humanidade",
        simbolos: ["Tocha", "Correntes", "Águia"],
        historia: "Prometeu é o titã que roubou o fogo dos deuses e o deu à humanidade, representando o conhecimento e a civilização. Moldou os humanos a partir de argila e os ensinou as artes. Zeus, enfurecido pelo roubo, acorrentou Prometeu a uma rocha no Cáucaso, onde uma águia devorava seu fígado todos os dias — que se regenerava à noite. Héracles o libertou séculos depois. Prometeu é o símbolo supremo da rebeldia em nome do bem.",
        poderes: ["Previsão do futuro", "Criação da humanidade", "Imortalidade", "Resistência à dor"],
        curiosidades: "O nome Prometeu significa 'aquele que pensa antes'. Seu irmão Epimeteu ('aquele que pensa depois') aceitou Pandora como presente dos deuses."
    },
    {
        nome: "Héstia",
        nomeRomano: "Vesta",
        emoji: "🏠",
        tipo: "olimpiano",
        dominio: "Lar, lareira e fogo sagrado",
        simbolos: ["Lareira", "Chama", "Chaleira", "Círculo"],
        historia: "Héstia é a deusa do lar e do fogo sagrado, a mais antiga e modesta dos deuses olímpicos. Primeira filha de Cronos e Reia (e primeira a ser engolida), foi também a última a ser libertada. Recusou propostas de Apolo e Poseidon, jurando virgindade eterna. Cedeu seu lugar no Olimpo para Dionísio sem ressentimento. Em cada cidade grega, seu fogo sagrado ardia no centro — se apagasse, era um presságio terrível.",
        poderes: ["Manter o fogo sagrado", "Proteção do lar", "Paz e harmonia", "Hospitalidade divina"],
        curiosidades: "Em Roma, as Vestais eram sacerdotisas dedicadas a manter o fogo de Vesta eternamente aceso. Se o fogo se apagasse, era sinal de grande desgraça."
    },
    {
        nome: "Eros",
        nomeRomano: "Cupido",
        emoji: "💘",
        tipo: "primordial",
        dominio: "Amor primordial, desejo e atração",
        simbolos: ["Arco e flechas", "Asas", "Coração", "Rosa"],
        historia: "Eros possui duas versões na mitologia. Como deus primordial, é uma das primeiras forças do universo — o amor que uniu o Caos para criar o cosmos. Na versão mais popular, é filho de Afrodite e Ares, um jovem alado que dispara flechas de ouro (amor) e chumbo (repulsa). Sua história mais famosa é com Psiquê: apaixonou-se por uma mortal e, após provações, Zeus concedeu imortalidade a Psiquê para ficarem juntos eternamente.",
        poderes: ["Induzir amor ou repulsa", "Flechas infalíveis", "Invisibilidade", "Voo"],
        curiosidades: "A palavra 'erótico' vem de Eros. Suas flechas de ouro causavam amor e as de chumbo causavam aversão."
    },
    {
        nome: "Gaia",
        nomeRomano: "Terra",
        emoji: "🌏",
        tipo: "primordial",
        dominio: "Terra, natureza e vida",
        simbolos: ["Terra", "Frutos", "Serpente", "Flores"],
        historia: "Gaia é a deusa primordial da Terra, uma das primeiras divindades a surgir do Caos. Mãe de Urano (Céu), com quem gerou os Titãs, os Ciclopes e os Hecatônquiros. Quando Urano aprisionou seus filhos monstruosos, Gaia armou Cronos com uma foice para castrá-lo. É a avó dos deuses olímpicos e a ancestral de quase todas as criaturas mitológicas. Representa a força vital da natureza e a mãe de todas as coisas.",
        poderes: ["Criação de vida", "Profecia (Oráculo de Delfos era originalmente seu)", "Controle da natureza", "Geração de criaturas"],
        curiosidades: "Gaia é a raiz da palavra 'geografia'. A hipótese de Gaia na ciência moderna sugere que a Terra funciona como um organismo vivo."
    },
    {
        nome: "Urano",
        nomeRomano: "Caelus",
        emoji: "🌌",
        tipo: "primordial",
        dominio: "Céu, estrelas e cosmos",
        simbolos: ["Céu estrelado", "Manto cósmico"],
        historia: "Urano é o deus primordial do Céu, filho e esposo de Gaia. Juntos geraram os Titãs, os Ciclopes e os Hecatônquiros. Temendo seus filhos monstruosos, Urano os aprisionou nas profundezas da terra (Tártaro). Gaia, furiosa, convenceu Cronos a castrá-lo com uma foice. Do sangue de Urano nasceram os Gigantes e as Erínias, e de seus restos lançados ao mar nasceu Afrodite. Após ser destronado, o céu se separou permanentemente da terra.",
        poderes: ["Controle do cosmos", "Geração de estrelas", "Poder primordial infinito"],
        curiosidades: "O planeta Urano foi nomeado em sua honra. É o único planeta do sistema solar com nome grego em vez de romano."
    },
    {
        nome: "Nix",
        nomeRomano: "Nox",
        emoji: "🌑",
        tipo: "primordial",
        dominio: "Noite, escuridão e mistério",
        simbolos: ["Véu escuro", "Estrelas", "Lua", "Morcego"],
        historia: "Nix é a deusa primordial da Noite, uma das forças mais antigas e poderosas do universo. Nascida do Caos, é mãe de inúmeras divindades: Tânatos (Morte), Hipnos (Sono), as Moiras (Destino), Nêmesis (Retribuição) e Éris (Discórdia). Até Zeus a temia e evitava confrontá-la. Viajava pelo céu em uma carruagem puxada por cavalos negros, espalhando a escuridão. Seu poder é tão antigo que precede os próprios deuses.",
        poderes: ["Controle da escuridão", "Poder sobre o destino", "Medo divino", "Invisibilidade na noite"],
        curiosidades: "Zeus, que não temia quase ninguém, hesitava em desafiar Nix. Quando quis punir Hipnos, recuou ao saber que era protegido por sua mãe."
    },
    {
        nome: "Hécate",
        nomeRomano: "Trivia",
        emoji: "🔮",
        tipo: "olimpiano",
        dominio: "Magia, encruzilhadas, fantasmas, lua negra e necromancia",
        simbolos: ["Tochas", "Chaves", "Cão", "Encruzilhada", "Lua negra"],
        historia: "Hécate é a deusa da magia, das encruzilhadas e do mundo entre os mundos. Filha dos titãs Perses e Astéria, foi a única titã que manteve seus poderes após a Titanomaquia — Zeus a respeitava tanto que preservou todos os seus domínios. Hécate habita os limiares: entre o mundo dos vivos e dos mortos, entre a luz e a escuridão, entre o conhecido e o desconhecido. É a guardiã das encruzilhadas de três caminhos, onde oferendas eram deixadas em sua honra. Como deusa tríplice (donzela, mãe e anciã), representa todos os ciclos da vida feminina. Acompanhou Deméter com suas tochas na busca por Perséfone e tornou-se companheira da rainha do submundo.",
        poderes: ["Magia suprema e feitiçaria", "Necromancia e comunicação com mortos", "Controle sobre fantasmas", "Domínio das encruzilhadas", "Visão entre mundos", "Poder sobre céu, terra e mar"],
        curiosidades: "Hécate é considerada a padroeira das bruxas na tradição wiccana. Oferendas nas encruzilhadas incluíam mel, ovos, peixe e bolos — conhecidas como 'Ceia de Hécate'. Seus cães uivavam à meia-noite, anunciando sua passagem. Os gregos acreditavam que ao ouvir cães uivando à noite, Hécate estava perto."
    },
    {
        nome: "Pan",
        nomeRomano: "Fauno",
        emoji: "🐐",
        tipo: "olimpiano",
        dominio: "Natureza selvagem, pastores, florestas, música rústica e fertilidade",
        simbolos: ["Flauta (siringe)", "Pinheiro", "Cabra", "Caverna"],
        historia: "Pan é o deus da natureza selvagem, dos pastores e dos rebanhos. Filho de Hermes (em uma das versões), nasceu com pernas, chifres e rabo de bode, assustando tanto sua própria mãe que ela fugiu. Hermes, porém, levou o bebê ao Olimpo, onde os deuses riram e o acolheram — especialmente Dionísio. Pan habita as florestas da Arcádia, onde toca sua flauta e persegue ninfas. Apaixonou-se pela ninfa Siringe, que, fugindo dele, foi transformada em caniços — dos quais Pan criou sua famosa flauta. Seu grito nas florestas causava terror repentino nos viajantes — origem da palavra 'pânico'.",
        poderes: ["Causar pânico (terror sobrenatural)", "Música encantadora", "Controle sobre a natureza selvagem", "Fertilidade", "Profecia"],
        curiosidades: "A palavra 'pânico' vem de Pan. Plutarco conta que durante o reinado de Tibério, um marinheiro ouviu uma voz misteriosa anunciar 'O Grande Pan está morto!' — cristãos interpretaram como o fim dos deuses pagãos. Na tradição wiccana, Pan é uma das faces do Deus Cornudo."
    },
    {
        nome: "Asclépio",
        nomeRomano: "Esculápio",
        emoji: "⚕️",
        tipo: "olimpiano",
        dominio: "Medicina, cura e ressurreição",
        simbolos: ["Bastão com serpente", "Ervas medicinais", "Galo", "Coroa de louros"],
        historia: "Asclépio é o deus da medicina, filho de Apolo e da mortal Coronis. Quando sua mãe morreu, Apolo resgatou o bebê e entregou-o ao centauro Quíron, o maior curandeiro do mundo mitológico. Sob a tutela de Quíron, Asclépio superou até seu mestre, tornando-se capaz não apenas de curar qualquer doença, mas de ressuscitar os mortos. Zeus, temendo que a humanidade se tornasse imortal e desafiasse a ordem natural, fulminou Asclépio com um raio. Apolo, enfurecido, matou os Ciclopes que forjaram o raio. Zeus então elevou Asclépio à constelação de Ofiúco (o Serpentário) como honra póstuma.",
        poderes: ["Cura de qualquer doença", "Ressurreição dos mortos", "Conhecimento de todas as ervas medicinais", "Cirurgia divina"],
        curiosidades: "O símbolo da medicina até hoje — o bastão de Asclépio com uma serpente — vem deste deus. Templos dedicados a ele (Asclepieia) eram os 'hospitais' da Grécia antiga, onde pacientes dormiam esperando que o deus os visitasse em sonhos com a cura. Hipócrates era considerado seu descendente."
    },
    {
        nome: "Nike",
        nomeRomano: "Vitória",
        emoji: "🏆",
        tipo: "olimpiano",
        dominio: "Vitória, triunfo e glória",
        simbolos: ["Asas", "Coroa de louros", "Palma", "Carro"],
        historia: "Nike é a deusa alada da vitória, filha do titã Palas e da oceânida Estige. Quando a Titanomaquia começou, Nike e seus irmãos — Zelo (Fervor), Cratos (Poder) e Bia (Força) — foram os primeiros a se juntar a Zeus, abandonando os titãs. Por essa lealdade, Zeus os manteve eternamente a seu lado. Nike voa sobre campos de batalha e competições, concedendo a vitória aos merecedores. Estátuas suas adornavam templos e estádios em toda a Grécia.",
        poderes: ["Conceder vitória em batalhas e competições", "Voo veloz", "Inspirar coragem e confiança", "Coroar vencedores"],
        curiosidades: "A famosa marca Nike leva o nome e o 'swoosh' (logo) desta deusa — representando o movimento de suas asas. A estátua 'Vitória de Samotrácia', uma das obras-primas do Louvre, retrata Nike. Nos Jogos Olímpicos antigos, uma estátua de Nike era carregada pelo vencedor."
    },
    {
        nome: "Selene",
        nomeRomano: "Luna",
        emoji: "🌝",
        tipo: "tita",
        dominio: "Lua, noite, ciclos e iluminação noturna",
        simbolos: ["Lua cheia", "Carruagem prateada", "Touro", "Manto"],
        historia: "Selene é a titã que personifica a própria Lua, filha dos titãs Hipérion e Teia, irmã de Hélio (Sol) e Eos (Aurora). Toda noite, Selene cruza o céu em sua carruagem prateada puxada por cavalos brancos (ou bois), banhando o mundo em luz prateada. Sua história mais famosa é o amor eterno pelo mortal Endimião, um pastor de beleza incomparável. Selene pediu a Zeus que o colocasse em sono eterno para que nunca envelhecesse, visitando-o todas as noites e gerando cinquenta filhas com ele. É a lua plena, diferente de Ártemis (lua crescente) e Hécate (lua negra).",
        poderes: ["Controle sobre as marés", "Iluminação noturna", "Influência sobre sonhos", "Ciclos lunares", "Encantamento e beleza"],
        curiosidades: "Selene, Ártemis e Hécate formam a 'Deusa Tríplice Lunar' na tradição mágica: Selene é a lua cheia (mãe), Ártemis a crescente (donzela) e Hécate a lua negra (anciã). A selenita (cristal) recebeu o nome em sua homenagem."
    },
    {
        nome: "Hélio",
        nomeRomano: "Sol",
        emoji: "🌞",
        tipo: "tita",
        dominio: "Sol, luz, visão e juramento",
        simbolos: ["Carruagem dourada", "Coroa de raios", "Quatro cavalos", "Olho"],
        historia: "Hélio é o titã que personifica o Sol, irmão de Selene e Eos. Todos os dias, atravessa o céu de leste a oeste em sua carruagem dourada puxada por quatro cavalos de fogo. À noite, retorna pelo rio Oceano em uma taça dourada. Como o Sol que tudo vê, Hélio era testemunha de todos os acontecimentos — foi ele quem revelou a Deméter que Hades havia raptado Perséfone, e a Hefesto que Afrodite o traía com Ares. Seu filho Faetonte pediu para guiar a carruagem solar e, sem controle, quase incendiou a terra — Zeus o fulminou para salvar o mundo.",
        poderes: ["Iluminação total", "Visão onisciente (tudo vê)", "Carruagem solar", "Juramento sagrado", "Calor e vida"],
        curiosidades: "A Ilha de Rodes era consagrada a Hélio, onde foi erguido o Colosso de Rodes — uma das sete maravilhas do mundo antigo — em sua honra. O nome 'hélio' (gás) e 'heliocêntrico' vêm deste deus."
    },
    {
        nome: "Eos",
        nomeRomano: "Aurora",
        emoji: "🌅",
        tipo: "tita",
        dominio: "Aurora, amanhecer e renovação",
        simbolos: ["Dedos rosados", "Carro alado", "Orvalho", "Açafrão"],
        historia: "Eos é a titã da Aurora, irmã de Hélio e Selene. Chamada por Homero de 'a dos dedos rosados', Eos abre os portões do céu todas as manhãs para que seu irmão Hélio passe com a carruagem solar. Afrodite a amaldiçoou com um desejo insaciável por homens mortais depois que Eos dormiu com Ares. Apaixonou-se pelo mortal Titono e pediu a Zeus que lhe desse imortalidade — mas esqueceu de pedir juventude eterna. Titono envelheceu indefinidamente até se transformar em uma cigarra, cantando para sempre.",
        poderes: ["Abrir o amanhecer", "Renovação diária", "Orvalho", "Esperança"],
        curiosidades: "A história de Eos e Titono é um dos mitos mais tristes da mitologia grega — um alerta sobre a importância de formular desejos com cuidado. O termo 'aurora boreal' vem de Aurora (Eos romana) e Boreas (vento norte)."
    },
    {
        nome: "Tique",
        nomeRomano: "Fortuna",
        emoji: "🎰",
        tipo: "olimpiano",
        dominio: "Sorte, fortuna, acaso e destino das cidades",
        simbolos: ["Roda da Fortuna", "Cornucópia", "Leme", "Bola/Esfera"],
        historia: "Tique é a deusa da fortuna, do acaso e da prosperidade. Filha de Hermes e Afrodite (ou de Oceano e Tétis em outras versões), ela distribui a sorte — boa ou má — de forma aparentemente aleatória. Representada com os olhos vendados, girando a Roda da Fortuna, Tique lembra que a sorte é caprichosa e pode mudar a qualquer momento. Cada cidade grega tinha sua própria Tique protetora, coroada com muros em forma de coroa. Em Roma, como Fortuna, tinha templos enormes e era uma das deusas mais adoradas.",
        poderes: ["Conceder ou retirar sorte", "Girar a Roda da Fortuna", "Proteger cidades", "Abundância ou escassez"],
        curiosidades: "A famosa 'Roda da Fortuna' do tarot vem diretamente de Tique/Fortuna. Em Roma, Fortuna tinha um oráculo famoso em Preneste. A expressão 'a sorte é uma roda' vem de sua iconografia."
    },
    {
        nome: "Nêmesis",
        nomeRomano: "Invidia",
        emoji: "⚖️",
        tipo: "primordial",
        dominio: "Retribuição divina, equilíbrio, vingança e justiça cármica",
        simbolos: ["Espada", "Balança", "Ramo de macieira", "Roda"],
        historia: "Nêmesis é a deusa da retribuição divina e do equilíbrio cósmico, filha de Nix (a Noite). Sua função é punir a hybris — a arrogância e o orgulho desmedido dos mortais e até dos deuses. Quando alguém acumula felicidade excessiva ou comete desrespeito aos deuses, Nêmesis restaura o equilíbrio. Não é uma deusa de vingança cega, mas de justiça cósmica — ela garante que ninguém tenha mais do que merece. Em Ramnunte, perto de Atenas, havia um templo famoso dedicado a ela.",
        poderes: ["Retribuição divina", "Equilíbrio cósmico", "Punição da arrogância", "Justiça inevitável"],
        curiosidades: "A palavra 'nêmesis' em português significa 'rival mortal' ou 'aquilo que causa a queda de alguém'. Zeus a perseguiu por amor, e ela se transformou em diversos animais para fugir — por fim, como gansa, botou o ovo de onde nasceu Helena de Troia (em uma versão do mito)."
    },
    {
        nome: "Hipnos",
        nomeRomano: "Somnus",
        emoji: "😴",
        tipo: "primordial",
        dominio: "Sono, descanso, sonhos e esquecimento",
        simbolos: ["Papoula", "Corno de sono", "Asas", "Rio Lete"],
        historia: "Hipnos é o deus do sono, irmão gêmeo de Tânatos (Morte) e filho de Nix (Noite). Habita uma caverna escura na entrada do submundo, cercada por papoulas e banhada pelo rio Lete (esquecimento). Nenhum som penetra sua morada — nem o canto do galo, nem o latido de cães. Hipnos é tão poderoso que pode adormecer mortais e deuses igualmente. Hera o convenceu a adormecer Zeus durante a Guerra de Troia para que ela pudesse ajudar os gregos. Pai de Morfeu (deus dos sonhos), Fobétor (pesadelos) e Fantaso (sonhos irreais).",
        poderes: ["Adormecer qualquer ser", "Controle total do sono", "Entrada nos sonhos", "Esquecimento"],
        curiosidades: "As palavras 'hipnose' e 'hipnótico' vêm de Hipnos. Sua morada na mitologia é quase idêntica ao conceito de 'anestesia geral' — escuridão, silêncio e inconsciência total. Os gregos acreditavam que dormir era um 'ensaio' para a morte."
    },
    {
        nome: "Tânatos",
        nomeRomano: "Mors",
        emoji: "🦋",
        tipo: "primordial",
        dominio: "Morte pacífica, passagem e transição",
        simbolos: ["Borboleta", "Tocha invertida", "Asas", "Papoula"],
        historia: "Tânatos é a personificação da morte pacífica, irmão gêmeo de Hipnos e filho de Nix. Diferente de percepções modernas, Tânatos não é terrível — ele é a morte serena, que chega gentilmente quando é hora. A morte violenta pertence às Keres, não a ele. Tânatos é representado como um jovem bonito com asas e uma tocha invertida (apagando a chama da vida). Foi enganado apenas duas vezes: por Sísifo, que o acorrentou (fazendo ninguém morrer por um tempo), e por Héracles, que lutou com ele para salvar Alceste.",
        poderes: ["Ceifar almas pacificamente", "Inescapabilidade", "Transição suave entre mundos", "Imortalidade"],
        curiosidades: "A borboleta é símbolo de Tânatos porque os gregos acreditavam que a alma (psyche) deixava o corpo na forma de borboleta. A palavra 'eutanásia' (boa morte) vem de 'eu' (boa) + 'thanatos' (morte). Na psicologia, Freud criou o conceito de 'Tânatos' como pulsão de morte."
    },
    {
        nome: "Iris",
        nomeRomano: "Iris",
        emoji: "🌈",
        tipo: "olimpiano",
        dominio: "Arco-íris, mensageira dos deuses e ligação céu-terra",
        simbolos: ["Arco-íris", "Jarro de água", "Asas douradas", "Caduceu"],
        historia: "Iris é a deusa do arco-íris e mensageira pessoal de Hera (enquanto Hermes serve Zeus). Filha do titã Taumas e da oceânida Electra, suas asas douradas a levam mais rápido que o vento entre o Olimpo, a Terra e o Submundo. O arco-íris é seu caminho visível quando viaja entre os mundos. Além de mensageira, Iris carrega água do rio Estige em seu jarro dourado — a água usada nos juramentos mais sagrados dos deuses. Jurar pelo Estige e quebrar o juramento significava perder a voz por sete anos.",
        poderes: ["Voo entre mundos", "Criar arco-íris", "Carregar água sagrada do Estige", "Mensagens divinas"],
        curiosidades: "A palavra 'iridescente' (que brilha como arco-íris) vem de Iris. A íris do olho também recebeu esse nome por suas cores. Na botânica, a flor íris foi nomeada em sua homenagem por suas pétalas coloridas."
    },
    {
        nome: "Eolo",
        nomeRomano: "Aéolo",
        emoji: "💨",
        tipo: "olimpiano",
        dominio: "Ventos, tempestades e navegação",
        simbolos: ["Saco dos ventos", "Harpa eólica", "Nuvens", "Bússola"],
        historia: "Eolo é o guardião dos ventos, que habita a ilha flutuante de Eólia. Zeus confiou a ele o controle dos quatro ventos: Bóreas (norte/frio), Noto (sul/tempestades), Euro (leste) e Zéfiro (oeste/suave). Eolo mantém os ventos presos em um saco de couro ou em uma caverna, liberando-os conforme necessário. Na Odisseia, Eolo ajudou Odisseu dando-lhe um saco com todos os ventos desfavoráveis presos — mas os tripulantes curiosos abriram o saco perto de casa, liberando os ventos e sendo arrastados de volta ao mar.",
        poderes: ["Controle absoluto dos ventos", "Tempestades e calmarias", "Proteger ou afundar navios", "Previsão do tempo"],
        curiosidades: "A 'harpa eólica' (instrumento tocado pelo vento) recebeu seu nome. O termo 'energia eólica' também vem de Eolo. Na meteorologia, a escala de ventos é medida com instrumentos chamados 'anemômetros' — de Anemos, palavra grega para vento."
    },
    {
        nome: "Quíron",
        nomeRomano: "Quíron",
        emoji: "🏹",
        tipo: "olimpiano",
        dominio: "Sabedoria, cura, ensino, artes e música",
        simbolos: ["Arco", "Ervas medicinais", "Lira", "Caverna"],
        historia: "Quíron é o mais sábio e nobre dos centauros, completamente diferente de seus parentes selvagens. Filho de Cronos (que se transformou em cavalo) e da ninfa Filira, nasceu como centauro contra a vontade dos pais. Criado por Apolo e Ártemis, tornou-se mestre em medicina, música, artes, profecia e caça. Sua caverna no Monte Pélion era uma escola para heróis: ensinou Aquiles, Jasão, Héracles, Asclépio e muitos outros. Quando foi atingido acidentalmente por uma flecha envenenada de Héracles, sua ferida (apesar da imortalidade) causava dor eterna. Quíron trocou sua imortalidade pela libertação de Prometeu, e Zeus o imortalizou como a constelação de Sagitário.",
        poderes: ["Cura suprema", "Profecia", "Sabedoria enciclopédica", "Musicalidade divina", "Imortalidade (cedida)"],
        curiosidades: "Em astrologia, Quíron é conhecido como o 'Curador Ferido' — um asteroide que representa onde temos nossas feridas mais profundas e como podemos curar os outros através delas. É um dos arquétipos mais importantes da psicologia junguiana."
    }
];
